name: Release

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

jobs:
  ReleaseMyIPTV:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: pnpm/action-setup@v4
      with:
        version: 9
        run_install: |
          - recursive: true
          - cwd: ./webui

    - name: Build webui
      working-directory: ./webui
      run: pnpm build

    - name: Get version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Build for amd64
      env:
        GOARCH: amd64
        GOOS: linux
      run: go build -ldflags "-s -w -X main.Version=${{ steps.get_version.outputs.VERSION }}" -o myiptv-${{ steps.get_version.outputs.VERSION }}-linux.amd64

    - name: Build for ARM64
      env:
        GOARCH: arm64
        GOOS: linux
      run: go build -ldflags "-s -w -X main.Version=${{ steps.get_version.outputs.VERSION }}" -o myiptv-${{ steps.get_version.outputs.VERSION }}-linux.arm64

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          myiptv-${{ steps.get_version.outputs.VERSION }}-linux.amd64
          myiptv-${{ steps.get_version.outputs.VERSION }}-linux.arm64
